### ISSUE TITLE
Not working with varnish 4.0

### ISSUE THREAD

**Issue by voxel01** [vimeo/libvmod-boltsort#5]
It's not working with varnish 4.0 there are compile error occuring while running configure as header file include/varnishapi.h from Varnish-source is missing. But that file is not there anymore.

checking for /usr/share/varnish/include/varnishapi.h... no
configure: error: "/usr/share/varnish" is not a Varnish source directory

I tried it with the rpm's as well as the source download from repo.varnish-cache.org

**Comment by vayam** [comment]
Are you are checking out master and not 3.0 branch?

Also boltsort is part of varnish std vmod. have you tried `std.querysort()`?

https://github.com/varnish/Varnish-Cache/blob/master/doc/changes.rst#changes-from-400-to-401-2014-06-24

**Comment by vayam** [comment]
can I close this??

**Comment by voxel01** [comment]
if it's in std now, yes
